apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-env
data:
  dev.env: |
    PORT="8000"
    PROJECT_NAME="Zerohertz's FastAPI Cookbook (dev)"
    VERSION="v0.1.3"
    PREFIX="/api"
    TZ="Asia/Seoul"
    DB_ECHO=true
    DB_TABLE_CREATE=true
    ALLOW_ORIGINS=http://localhost:5173,https://zerohertz.vercel.app
  prod.env: |
    PORT="8000"
    PROJECT_NAME="Zerohertz's FastAPI Cookbook (prod)"
    VERSION="v0.1.3"
    PREFIX=""
    TZ="Asia/Seoul"
    DB_ECHO=false
    DB_TABLE_CREATE=false
    ALLOW_ORIGINS=http://localhost:5173,https://zerohertz.vercel.app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql
data:
  TYPE: "postgresql"
  DRIVER: "asyncpg"
  HOST: "postgresql"
  PORT: "5432"
  DATABASE: "fastapi"
